package uz.pdp.bot;

public interface BotState {
    String START="START";
    String CHOOSE_LANG="CHOOSE_LANG";
    String SHARE_CONTACT="SHARE_CONTACT";
    String ENTER_CODE="ENTER_CODE";
    String SHOW_MENU="SHOW_MENU";
    String ABOUT_US="ABOUT_US";
    String SOCIAL_NETS="SOCIAL_NETS";
    String SHOW_BASKET="SHOW_BASKET";
    String SHOW_ORDER_HISTORY="SHOW_ORDER_HISTORY";
    String CHANGE_LANG="CHANGE_LANG";
    String RESEND_CODE="RESEND_CODE";
    String CHOOSE_GENDER="CHOOSE_GENDER";
    String SHOW_PRODUCTS="SHOW_PRODUCTS";
    String ENTER_AMOUNT="ENTER_AMOUNT";
    String SHARE_LOCATION="SHARE_LOCATION";
    String CHOOSE_PAY_TYPE="CHOOSE_PAY_TYPE";
}
